### PR TITLE
Design: Create designs for the Navigation component

### LINKED ISSUE #32: Design: Create designs for the Navigation component
## Issue summary

There is currently no design for the navigation component and in order for the project to have a uniform styleguide, a design has to be created for each of the components.

## Proposed fix

Create a design for the navigation component using the colors of the project which is already given in the README. 

## Tasks

 - [ ] Navigation bar
 - [ ] Mega menu
 - [ ] Breadcrumbs
 - [ ] Sidebar

NB: There is no font family chosen yet, so you would have to pick one yourself

After you start working on the issue, i.e designing, drop a link to the figma page here and give me alongside @AdityaSingh-02 and @purnima143 edit access

### PR DESCRIPTION
**Pull request by Rishika-S-V**
Fixes #32

## Description
The Navigation Component is a crucial element of the application's user interface that facilitates seamless navigation and enhances the overall user experience. It encompasses various interactive elements such as the Navbar, Megamenu, Sidebar, and Breadcrumbs, which work together to provide users with intuitive and efficient ways to navigate through different sections and features of the application.

## Motivation
The motivation behind these updates is to address usability concerns and provide users with a more streamlined and intuitive navigation experience. The previous navigation components had limitations in terms of visual clarity, functionality, and responsiveness. By refining the Navbar, Megamenu, and Sidebar, and introducing Breadcrumbs, we aim to enhance user satisfaction, improve navigation efficiency, and promote a cohesive user experience.

## Changes Made
- The design of the Navbar for a more polished and modern appearance.
- Refined the Megamenu to improve category organization, labelling, and visuals.
- Enhanced the Sidebar for better usability, accessibility, and content organization.
- Added Breadcrumbs as a new navigation element to provide contextual navigation options.

## Checklist
- [x] Code follows the project's style guidelines.
- [x] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if applicable. Mark ☑️ in the component section of the readme.Md file.
- [x] All new and existing tests pass.
- [ ] The code has been reviewed by at least one other developer.
- [x] The pull request is linked to the corresponding issue, if applicable.

### Navigation
The Navbar has undergone refinements to improve its visual appeal and functionality. The design changes include adjusting the alignment and spacing of navigation links, enhancing the responsiveness for different screen sizes, and optimizing the overall layout. These updates provide a more polished and modern Navbar that aligns with the application's visual language.

**Navigation - Light Mode**
image

**Navigation - Dark Mode**
image

### Megamenu
The Megamenu has been enhanced to offer a more intuitive and user-friendly dropdown experience. It now includes improved category organization, clearer labelling, and enhanced visuals. The updated Megamenu allows users to quickly find and access relevant subcategories and information, improving the overall navigation experience.

**Megamenu - Light Mode**
image

**Megamenu - Dark Mode**
image

### Breadcrumbs
Breadcrumbs have been added as a new navigation element to provide users with a clear path and context within the application's hierarchy. Breadcrumbs help users understand their current location and provide quick navigation options to higher-level pages or sections.

**Breadcrumbs - Light Mode**
image

**Breadcrumbs - Dark Mode**
image

### Sidebar
The Sidebar is to improve its usability and accessibility. The design includes clearer icons and labels, improved hierarchy, and a collapsible/expandable feature for better content organization. These changes make it easier for users to navigate through different sections of the application and access specific features or pages.

**Sidebar - Light Mode**
image

**Sidebar - Dark Mode**
image

### CODE REVIEW

**Comment by Lovelyfin00** [comment]
Hey @Rishika-S-V 
Can you close this and open a new PR against the dev branch

**Comment by Rishika-S-V** [comment]
@Lovelyfin00 base has been changed to `dev` branch

**Comment by Lovelyfin00** [comment]
Great
I'll merge after checking it on my local machine

**Comment by Lovelyfin00** [comment]
LGTM

**Pull request merged**
