### PR TITLE
Added 6 new button styles

### LINKED ISSUE #31: Adding More Button Styles
Wants to add more button styles under Gssoc'23

### PR DESCRIPTION
**Pull request by ojasaklechayt**
Fixes #31 

I have created and added more button styles in my PR. I have made the detailed explanation through diagram and discussion is in Issue Number: #31

### CODE REVIEW

**Comment by Lovelyfin00** [comment]
Nice stuff you got here🎉
Just some suggestions and comments

- For all the buttons that are rounded, they should be inside the rounded story and can have all the colors and the large size too. And also, I don't think we need any button to have a shadow for now until the design accounts for it.

**Comment by ojasaklechayt** [comment]
> Nice stuff you got here🎉 Just some suggestions and comments
> 
> * For all the buttons that are rounded, they should be inside the rounded story and can have all the colors and the large size too. And also, I don't think we need any button to have a shadow for now until the design accounts for it.

Okay, I will make the changes

**Comment by ojasaklechayt** [comment]
> Nice stuff you got here🎉 Just some suggestions and comments
> 
> * For all the buttons that are rounded, they should be inside the rounded story and can have all the colors and the large size too. And also, I don't think we need any button to have a shadow for now until the design accounts for it.

Updated

**Comment by Lovelyfin00** [comment]
You've done a great job🎉
What I want you to do next is put all the round buttons inside of the button story. I don't want each of them to be a story on their own.

**Comment by ojasaklechayt** [comment]
> You've done a great job🎉 What I want you to do next is put all the round buttons inside of the rounded story. I don't want each of them to be a story on their own.

How can I do it ? Are there any resources to follow ?

**Comment by Lovelyfin00** [comment]
I'll review it and drop feedback. Thanks

**Comment by Lovelyfin00** [comment]
Ok, I have checked it out and that's not what I meant
Inside of the button story, Have a sub story called `Round` which is where I wrote Round
Now inside of the Round story, you can populate it with different round buttons with colors instead of just a single button

tempsnip


Use this for reference
https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/button.stories.tsx

**Comment by ojasaklechayt** [comment]
> Ok, I have checked it out and that's not what I meant
> Inside of the button story, Have a sub story called `Round` which is where I wrote Round
> Now inside of the Round story, you can populate it with different round buttons with colors instead of just a single button
> 
> tempsnip
> 
> 
> Use this for reference
> https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/button.stories.tsx

Hi! I tried doing it but I am unable to change it.

**Comment by ojasaklechayt** [comment]
@purnima143 I have done the changes + there were some merge conflicts due to which I had to close the pr/. I have reopened it.

**Comment by Lovelyfin00** [comment]
Thanks for sticking to this @ojasaklechayt 
You would need to open a new PR with these changes and it should be against the dev branch instead of master
image

**Comment by ojasaklechayt** [comment]
> 

Okay I shall close this pr then

**Pull request closed without merging**
