### PR TITLE
Making a design system for Pluto UI and implement them

### LINKED ISSUE #11: Making a design system for Pluto UI and implement them
I want to work on design system for this project .

We will be covering all the major thing required for E-Commerce UI libraries . 

Goal of the UI lib : An E-Commerce website can be made just by our components alone . No additional coding should be required . 

Needs : 1) Documented & Well designed components
2) Components independent of each other 
3) Consistent design

### PR DESCRIPTION
**Pull request by Rishika-S-V**
Fixes #11

### CODE REVIEW

**Comment by Lovelyfin00** [comment]
Hey @Rishika-S-V 
In order for this to be a valid pr, add an explanation of what you did and include screenshots

**Comment by Rishika-S-V** [comment]
# Design System for Pluto UI

## Colour System
The colour system introduces a harmonious palette that brings visual consistency and clarity to the application. It ensures that colours are thoughtfully chosen to convey meaning and create engaging experiences.

Colors

## Border Radii
The border radii modifications refine the shape and form of elements, giving them a polished and modern appearance. This unified approach ensures that corners and edges are consistent across the interface, promoting a cohesive visual language.

Border radius

## Elevation
Elevation adjustments within the Design System contribute to a more intuitive user experience. Interactions become more tangible by carefully defining the depth and shadowing of elements, providing users with a sense of hierarchy and depth as they navigate through the application.

Elevation

## Display Font
The Display fonts play a pivotal role in the aesthetic appeal of the interface. The updated fonts strike a balance between legibility and style, enhancing readability and evoking a sense of brand identity. These changes will bring a refined and professional touch to the overall design.

Display Font

## Headings & Paragraph
Headings and paragraph sizes are being optimized to establish a clear hierarchy and improve content presentation. The updated sizes and spacing ensure that information is appropriately emphasized and easily scannable, enhancing the user's ability to quickly grasp the key points.

Headings

Paragraph

**Comment by Lovelyfin00** [comment]
Thank you so much for this
It's looking pretty solid🎉🎉

@purnima143 @AdityaSingh-02 
What do you guys think?

**Comment by AdityaSingh-02** [comment]
Looks pretty good we can go for it

**Comment by Lovelyfin00** [comment]
Awesome!

**Comment by Lovelyfin00** [comment]
Hey @Rishika-S-V 
Can you put all the pdfs inside a sub folder called maybe design system?
This is because other designs would also be in this design folder and we don't want everything to be clustered together

**Comment by Rishika-S-V** [comment]
Updated the folder structure

**Comment by Lovelyfin00** [comment]
Great thanks! Merging now

**Comment by Lovelyfin00** [comment]
Forgot to remind you. Please always delete your package-lock.json file

**Comment by Lovelyfin00** [comment]
This looks super good
Great job @Rishika-S-V

**Pull request merged**
