### PR TITLE
Added 6 new button styling

### PR DESCRIPTION
**Pull request by ojasaklechayt**
Fixes: #31 

I have created and added more button styles in my PR. I have made the detailed explanation through diagram and discussion is in Issue Number: #31

### CODE REVIEW

**Comment by ojasaklechayt** [comment]
@Lovelyfin00 can you please check ?

**Comment by Lovelyfin00** [comment]
Hey @ojasaklechayt 
This looks super perfect
Thanks a lot for sticking to this.
What do you think @AdityaSingh-02 @purnima143 

<br/>

image

**Comment by sandygudie** [comment]
**Suggestion**
I would suggest we have a generic round button component rather than variants of round buttons. I mean rather than "round secondary", "round warning, "round success", "round light", "round-small", "square primary" etc  let's just have a round button component added to the existing list.

**Comment by ojasaklechayt** [comment]
@Lovelyfin00 any updates regarding this ?

**Comment by ojasaklechayt** [comment]
@AdityaSingh-02 @purnima143

**Review by purnima143 — APPROVED** [review]

**Comment by purnima143** [comment]
Done a pretty good job @ojasaklechayt

**Pull request merged**
